export const clerkSpanishLocalization = {
  locale: "es-AR",
  socialButtonsBlockButton: "Continuar con {{provider|titleize}}",
  dividerText: "o",
  formFieldLabel__emailAddress: "Email",
  formFieldLabel__emailAddresses: "Emails",
  formFieldLabel__emailAddress_username: "Email o usuario",
  formFieldLabel__password: "Contraseña",
  formFieldLabel__currentPassword: "Contraseña actual",
  formFieldLabel__newPassword: "Nueva contraseña",
  formFieldLabel__confirmPassword: "Confirmar contraseña",
  formFieldLabel__firstName: "Nombre",
  formFieldLabel__lastName: "Apellido",
  formFieldLabel__phoneNumber: "Teléfono",
  formFieldLabel__username: "Usuario",
  formFieldInputPlaceholder__emailAddress: "tu@email.com",
  formFieldInputPlaceholder__emailAddress_username: "Email o usuario",
  formFieldInputPlaceholder__password: "Tu contraseña",
  formFieldInputPlaceholder__firstName: "Tu nombre",
  formFieldInputPlaceholder__lastName: "Tu apellido",
  formFieldError__notMatchingPasswords: "Las contraseñas no coinciden.",
  formFieldAction__forgotPassword: "Olvidé mi contraseña",
  formButtonPrimary: "Continuar",
  formButtonPrimary__verify: "Verificar",
  backButton: "Volver",
  footerActionLink__useAnotherMethod: "Usar otro método",
  badge__thisDevice: "Este dispositivo",
  badge__you: "Vos",
  paginationButton__previous: "Anterior",
  paginationButton__next: "Siguiente",
  signIn: {
    start: {
      title: "Iniciar sesión",
      titleCombined: "Iniciar sesión o registrarse",
      subtitle: "Bienvenido de nuevo",
      subtitleCombined: "Continuá para acceder a Satix",
      actionText: "¿No tenés cuenta?",
      actionLink: "Registrate",
      actionLink__use_email: "Usar email",
      actionLink__use_phone: "Usar teléfono",
      actionLink__use_username: "Usar usuario",
      actionLink__use_email_username: "Usar email o usuario",
      actionLink__use_passkey: "Usar passkey",
    },
    password: {
      title: "Ingresá tu contraseña",
      subtitle: "Ingresá la contraseña de tu cuenta",
      actionLink: "Usar otro método",
    },
    forgotPassword: {
      title: "Restablecer contraseña",
      subtitle: "Te enviaremos instrucciones para recuperar el acceso.",
      subtitle_email: "Te enviaremos un código a tu email.",
      subtitle_phone: "Te enviaremos un código a tu teléfono.",
      formTitle: "Código de verificación",
      resendButton: "Reenviar código",
    },
    resetPassword: {
      title: "Crear nueva contraseña",
      formButtonPrimary: "Guardar contraseña",
      successMessage: "Tu contraseña fue actualizada.",
      requiredMessage: "Ingresá una nueva contraseña.",
    },
    emailCode: {
      title: "Revisá tu email",
      subtitle: "Enviamos un código de verificación.",
      formTitle: "Código de verificación",
      resendButton: "Reenviar código",
    },
    emailLink: {
      title: "Revisá tu email",
      subtitle: "Te enviamos un enlace para iniciar sesión.",
      formTitle: "Enlace enviado",
      formSubtitle: "Abrí el enlace desde el mismo dispositivo.",
      resendButton: "Reenviar enlace",
      verified: {
        title: "Email verificado",
        subtitle: "Ya podés continuar.",
      },
      loading: {
        title: "Verificando...",
        subtitle: "Esto puede tardar unos segundos.",
      },
      failed: {
        title: "No pudimos verificar el enlace",
        subtitle: "Volvé a intentarlo.",
      },
      expired: {
        title: "El enlace expiró",
        subtitle: "Solicitá uno nuevo para continuar.",
      },
    },
    phoneCode: {
      title: "Revisá tu teléfono",
      subtitle: "Enviamos un código de verificación.",
      formTitle: "Código de verificación",
      resendButton: "Reenviar código",
    },
    alternativeMethods: {
      title: "Usar otro método",
      subtitle: "Elegí otra forma de iniciar sesión.",
      actionLink: "Volver",
      actionText: "¿Querés volver?",
      blockButton__emailCode: "Enviar código a {{identifier}}",
      blockButton__emailLink: "Enviar enlace a {{identifier}}",
      blockButton__phoneCode: "Enviar código por SMS a {{identifier}}",
      blockButton__password: "Ingresar contraseña",
      blockButton__passkey: "Usar passkey",
      blockButton__totp: "Usar aplicación autenticadora",
      blockButton__backupCode: "Usar código de respaldo",
    },
    noAvailableMethods: {
      title: "No hay métodos disponibles",
      subtitle: "No encontramos un método para iniciar sesión.",
      message: "Contactá a soporte si necesitás ayuda.",
    },
  },
  signUp: {
    start: {
      title: "Crear cuenta",
      titleCombined: "Crear cuenta o iniciar sesión",
      subtitle: "Empezá a usar Satix",
      subtitleCombined: "Continuá para crear tu cuenta",
      actionText: "¿Ya tenés cuenta?",
      actionLink: "Iniciá sesión",
      actionLink__use_email: "Usar email",
      actionLink__use_phone: "Usar teléfono",
    },
    continue: {
      title: "Completá tus datos",
      subtitle: "Necesitamos algunos datos para crear tu cuenta.",
      actionText: "¿Ya tenés cuenta?",
      actionLink: "Iniciá sesión",
    },
    emailCode: {
      title: "Verificá tu email",
      subtitle: "Enviamos un código de verificación.",
      formTitle: "Código de verificación",
      formSubtitle: "Ingresá el código que recibiste por email.",
      resendButton: "Reenviar código",
    },
    emailLink: {
      title: "Revisá tu email",
      subtitle: "Te enviamos un enlace de verificación.",
      formTitle: "Enlace enviado",
      formSubtitle: "Abrí el enlace para continuar.",
      resendButton: "Reenviar enlace",
      verified: {
        title: "Email verificado",
      },
      loading: {
        title: "Verificando...",
      },
    },
    phoneCode: {
      title: "Verificá tu teléfono",
      subtitle: "Enviamos un código de verificación.",
      formTitle: "Código de verificación",
      formSubtitle: "Ingresá el código que recibiste.",
      resendButton: "Reenviar código",
    },
  },
} as const;
