export { default as Contact } from "./Contact";
export { default as ExtraTools } from "./ExtraTools";
export { default as Faq } from "./Faq";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as HowItWorks } from "./HowItWorks";
export { default as Navbar } from "./Navbar";
export { default as Pricing } from "./Pricing";
export { default as Testimonials } from "./Testimonials";
